spring.application.name=valtxarq
server.port=${AGENTESERVER_PORT:8091}

app.api.base-url=${API_BASE_URL:http://localhost:${server.port}}

# Configuracion de conexion a PostgreSQL
spring.datasource.url=${POSTGRESQL_URL:jdbc:postgresql://localhost:5432/valtxarq}
spring.datasource.username=${POSTGRESQL_USERNAME:postgres}
spring.datasource.password=${POSTGRESQL_PASSWORD:admin}

spring.datasource.driver-class-name=org.postgresql.Driver


# Configuracion JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# 1. Dialecto especifico para PostgreSQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.open-in-view=false














